language: r
dist: trusty
bioc_required: true
warnings_are_errors: true
cache:
  directories:
    - $HOME/.cache/hdf5
    - $HOME/R/Library
services:
  - docker
addons:
  apt:
    packages:
      - libssh-dev  # PRISM > ssh > libssh-dev
before_install:
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - install_hdf5
install:
 - apt-get install -y python3.6
 - wget -qO- https://bootstrap.pypa.io/get-pip.py | python3.6 --user
 - pip3 install . --user
 - # use_dynverse_devel
 - install_cran devtools
 - R -e 'devtools::install_github("dynverse/dyncli", dep = TRUE)'
script:
  - python3.6 setup.py test
jobs:
  include:
    - stage: prepare hdf5
      install:
        - echo Skip
      script:
        - echo Skip
    - stage: prepare cache
      script:
        - echo Skip
    - stage: test