language: python
python:
- "3.6"
cache:
  directories:
    - $HOME/.cache/hdf5
    - $HOME/R/Library
    - $HOME/.pip
services:
  - docker
before_install:
  - export R_LIBS_USER=$HOME/R/Library
  - source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
  - sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/'
  - sudo apt-get install -y r-base r-base-dev
  - install_cran devtools
  - install_cran BiocManager
  - R -e 'BiocManager::install()'
  - install_hdf5
install:
 - # use_dynverse_devel
 - install_github_withdeps dynverse/dyncli
 - pip install . --user
script:
  - python setup.py test
jobs:
  include:
    - stage: prepare hdf5
      install:
        - echo Skip
      script:
        - echo Skip
    - stage: prepare cache
      script:
        - echo Skip
    - stage: test
